export type MarketData = {
	isMintable: string
	tokensBurned: string
	tokensBurnedPercentage: string
	lpBurnt: string
	coinSupply: string
	fullyDilutedMarketCap: string
	marketCap: string
	totalLiquidityUsd: string
	timeCreated: string
	coin: string
	coinDev: string
	price5mAgo: string
	price1hAgo: string
	price6hAgo: string
	price24hAgo: string
	percentagePriceChange5m: string
	percentagePriceChange1h: string
	percentagePriceChange6h: string
	percentagePriceChange24h: string
	buyVolume5m: string
	buyVolume1h: string
	buyVolume6h: string
	buyVolume24h: string
	sellVolume5m: string
	sellVolume1h: string
	sellVolume6h: string
	sellVolume24h: string
	volume5m: string
	volume1h: string
	volume6h: string
	volume24h: string
	coinPrice: string
	top10HolderPercentage: string
	top20HolderPercentage: string
	coinDevHoldings: string
	coinDevHoldingsPercentage: string
}