import type { Metadata } from "next"
import "@/app/globals.css"
import { SessionProvider } from "next-auth/react"
import { Toaster } from "react-hot-toast"
import { ReactScan } from "@/components/utils/react-scan"
import { TailwindIndicator } from "@/components/utils/tailwind-indicator"
import { TwitterAuthProvider } from "@/context/twitter.context"
import { geistMono, geistSans } from "@/fonts"
import { ApolloProvider } from "@/providers/apollo-provider"
import SuiProvider from "@/providers/sui-provider"
import { ThemeProvider } from "@/providers/theme-provider"
import { cn } from "@/utils"

export const metadata: Metadata = {
	title: "xPump Launchpad",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<ReactScan />
			<body className={cn(geistSans.variable, geistMono.variable, "antialiased")}>
				<ThemeProvider attribute="class" defaultTheme="dark" disableTransitionOnChange>
					<SessionProvider>
						<TwitterAuthProvider>
							<ApolloProvider>
								<SuiProvider>
									{children}

									<TailwindIndicator />
									<Toaster
										position="bottom-center"
										reverseOrder={true}
										toastOptions={{
											style: {
												backgroundColor: "var(--card)",
												color: "var(--foreground)",
												padding: "12px 12px",
												border: "1px solid var(--border)",
											},
										}}
									/>
								</SuiProvider>
							</ApolloProvider>
						</TwitterAuthProvider>
					</SessionProvider>
				</ThemeProvider>
			</body>
		</html>
	)
}
