import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import { geistMono, geistSans } from "@/fonts";
import { cn } from "@/utils"
import { ThemeProvider } from "@/providers/theme-provider";
import { TailwindIndicator } from "@/components/utils/tailwind-indicator";
import { WalletContextProvider } from "@/context/wallet.context";
import SuiProvider from "@/providers/sui-provider";

export const metadata: Metadata = {
    title: "Coda Labs' Dapp Starter",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    geistSans.variable,
                    geistMono.variable,
                    "antialiased"
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    disableTransitionOnChange
                >
                    <SuiProvider>
                        {children}

                        <TailwindIndicator />
                        <Toaster
                            position="bottom-center"
                            reverseOrder={true}
                            toastOptions={{
                                style: {
                                    backgroundColor: "var(--card)",
                                    color: "var(--foreground)",
                                    padding: "12px 12px",
                                    border: "1px solid var(--border)",
                                },
                            }}
                        />
                    </SuiProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
