import type { Metadata } from "next";
import "@/app/globals.css";
import { Toaster } from "react-hot-toast";
import { geistMono, geistSans } from "@/fonts";
import { cn } from "@/utils"
import { ThemeProvider } from "@/providers/theme-provider";
import { TailwindIndicator } from "@/components/utils/tailwind-indicator";
import { WalletContextProvider } from "@/context/wallet.context";
import SuiProvider from "@/providers/sui-provider";
import { TwitterAuthProvider } from "@/context/twitter.context";

export const metadata: Metadata = {
    title: "xPump Launchpad",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={cn(
                    geistSans.variable,
                    geistMono.variable,
                    "antialiased"
                )}
            >
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    disableTransitionOnChange
                >
                    <TwitterAuthProvider>
                        <SuiProvider>
                            {children}

                            <TailwindIndicator />
                            <Toaster
                                position="bottom-center"
                                reverseOrder={true}
                                toastOptions={{
                                    style: {
                                        backgroundColor: "var(--card)",
                                        color: "var(--foreground)",
                                        padding: "12px 12px",
                                        border: "1px solid var(--border)",
                                    },
                                }}
                            />
                        </SuiProvider>
                    </TwitterAuthProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
